apiVersion: v1
kind: Service
metadata:
  name: be-service
  labels:
    app: be-service
spec:
  type: LoadBalancer
  ports:
  - name: be-app
    port: 3000
    targetPort: 3000
  selector:
    app: be-app
